### ISSUE TITLE
Awards System

### ISSUE THREAD

**Issue by yekenuk** [yekenuk/Weight-Loss-Tracker#173]
Allow awards to be issued to users for the following:

- Meeting certain increases or decreases in weight.
- Meeting certain increases or decreases in percentage of weight.
- Meeting certain increases or decreases in BMI.
- Meeting a certain BMI label.

Upon an award being issued;

- Log it against user record (so it can't be re-issued)
- Send an email
- Add relevant badges / titles to their user record
- Create a shortcode to display one or more badges / awards

**Comment by worldsdream** [comment]
A very nice feature. Love it.

**Comment by yekenuk** [comment]
Thanks! Hoping to release it within the next 3-4 weeks! 🤞
