### ISSUE TITLE
Subadmins / reseller

### ISSUE THREAD

**Issue by worldsdream** [yekenuk/Weight-Loss-Tracker#180]
Is it possible that we have a subadmins/reseller accounts. 

For example: admin logs in. Admin creates 2 subadmins/resellers called: John and Suzan. 

John is able to make new clients in the dashboard. The client can login and make use of the weight tracker. The subadmin/reseller John can see only his clients. The same goes for subadmin/reseller Suzan. She can make new clients and only she can see her clients. 

Ofcourse the admin can see everything. The admin can move clients from one reseller/subadmin to another reseller/subadmin. For example. Client of John goes to Suzan and vice versa. 

Also we can move the clients from reseller/subadmins to the main admin. 

What do you think? Possible? I love this feature!

**Comment by yekenuk** [comment]
mmm... this is possible... but it's a large change to how the plugin works at its core 😬 I'd have to think about it... since you're the first to suggest it, I'm not sure there is much demand...

**Comment by worldsdream** [comment]
You and me share the same thought. “Everything is possible”.

Just giving you the most interesting ideas. If others had my mind. They would have told you before lol.

**Comment by yekenuk** [comment]
Thinking this over, I think I'll close it for now... it's not something I plan to develop into the plugin. Although a good idea!
