### ISSUE TITLE
[BUG] Clear target does not work.

### ISSUE THREAD

**Issue by worldsdream** [yekenuk/Weight-Loss-Tracker#182]
When clicking on the button "Clear Target". The target does not clear.

Latest wordpress v4.9.8
Latest pro plus v6.1.1

**Comment by worldsdream** [comment]
Ah I see. 

I have to click on the button clear target. Then go down and click on the SAVE button. 

Please please change this behaviour. Because looking at UX this is misleading. 

When you set target. You fill in the target and click on the button set target. You see the target inserted. WITHOUT going down and clicking on the save button!!

So a normal person, would think that it works the same if you clear the target. Click on clear target button. It will clear. But no, it does not. We have to go down and click on save button. 

What needs to be done:
Click on clear target. It shows that it’s cleared. Empty field. Target weight is gone.

**Comment by worldsdream** [comment]
I am logged in as admin or as an user. I click on clear target. Nothing happens. it should refresh the page or an ajax frame that will clear it.

**Comment by yekenuk** [comment]
Yeah I think it is clearing the value... but doesn't refresh the page or do anything visually to indicate it. I'll look at changing this.

**Comment by yekenuk** [comment]
Released early as part of 7.0.4 (#198)
