### ISSUE TITLE
Add the Dutch translation to the Dutch Formal language

### ISSUE THREAD

**Issue by worldsdream** [yekenuk/Weight-Loss-Tracker#183]
When I enable Dutch Formal, the plugin does not show in Dutch.
When I enable Dutch language, the plugin does show in Dutch.

Can you copy the po/mo language files from Dutch to the Dutch Formal? When I or others select Dutch Formal in WP, they will see the plugin in the Dutch. Right now it's in English.

**Comment by yekenuk** [comment]
Is this holding you back? Or can I put it out in the net major release?

**Comment by worldsdream** [comment]
Not holding me back. Just to make this plugin function better. Next major release is perfect.

**Comment by yekenuk** [comment]
Released early as part of 7.0.4 (#198)
