### ISSUE TITLE
Share awards across social media

### ISSUE THREAD

**Issue by mybestrong** [yekenuk/Weight-Loss-Tracker#210]
Add the ability to share the image of the award given to a user, from the email notification sent to them, across social media platforms.

Also the facility to customise that email from the admin.

**Comment by yekenuk** [comment]
As suggested via email, I will add a "Award URL" field for Awards.

This will allow a link to a page etc where you can add your own text and social share icons :)

**Comment by yekenuk** [comment]
URL field added to awards in #222
