### ISSUE TITLE
Support for # id hashtag in URL while submitting forms

### ISSUE THREAD

**Issue by madmonkey2** [yekenuk/Weight-Loss-Tracker#223]
Just a minor issue that I faced recently… Is there a way how to add hashtag # from the current URL to the URL of the input buttons in the forms?

Here is the thing.. I have a the wlt-table placed in an accordion tab, hence the URL is something like http://blabla.com/page#my-tab. When I click “edit the record”, I get directed to http://blabla.com/page??ws-edit-entry=9&user-id=1&redirect=aHR0c ..I need that this URL contains also the id hashtag so that the correspondent tab opens accordingly.

**Comment by yekenuk** [comment]
Add this as a filter instead:

File includes/core.php line 309
change "esc_attr( get_permalink() )," to "apply_filters('wlt_form_url', esc_attr( get_permalink() )),"

**Comment by yekenuk** [comment]
This will be in 7.0.13 (going out soon)
