### ISSUE TITLE
button not appear properly.

### ISSUE THREAD

**Issue by rosdisulaiman** [yekenuk/Weight-Loss-Tracker#3]
button problem - css for clear button appear hidden.
how can i allign and make sure the button appear correctly and change the color?

![button](https://cloud.githubusercontent.com/assets/24992073/21752244/c60fe31e-d60f-11e6-9cc5-5f998e81ef09.png)

**Comment by yekenuk** [comment]
This is being tracked on Wordpress.org:

https://wordpress.org/support/topic/button-displayed-weird/

**Comment by yekenuk** [comment]
Closed.
