### ISSUE TITLE
Not displaying tracker 

### ISSUE THREAD

**Issue by fitnessflex** [yekenuk/Weight-Loss-Tracker#4]
Hi, 

On my Page i just get a loading button. 

Are you aware of wha this issue is? are there any plugins this does not work with?

It appeared to work for a few days then just stopped I havent downloaded any new plugins?

Many thanks
Becky 
![screen shot 2017-01-10 at 10 48 02](https://cloud.githubusercontent.com/assets/25030298/21803663/f69a8638-d722-11e6-986a-08383d213cd0.png)

**Comment by yekenuk** [comment]
Thanks for letting me know.

Sometimes see this and it's usually due to another plugin causing an issue (or a theme)... have you updated any? Can you try (if not a live site) with the Twenty Sixteen theme?

Here is a list known compatibility issues:

https://github.com/yekenuk/Weight-Loss-Tracker/wiki/Compatibility-Issues

**Comment by fitnessflex** [comment]
Sorry I'm new to this, no I don't have any of those plugins. 

What do you mean by  Twenty Sixteen theme?

**Comment by fitnessflex** [comment]
We currently use Optimize press & Membarium

**Comment by yekenuk** [comment]
Twenty Sixteen is a standard theme (Appearances > Themes) that comes with Wordpress. I know that it works with that theme. So, if you're able to switch to it and it works, then we know it could be your theme causing an issue.

As for the plugins, are you able to quickly turn them off, check the weight loss tracker, then turn back on? Tell me if it works when one of the plugins is off?

If neither of them work, I'm afraid I would need an example link and admin access. Send these via email email@yeken.uk

**Comment by fitnessflex** [comment]
Hi

I cant change the theme as it will change my whole website and I dont want that?

Ive deactivated all of my plugins and its not that? 

If it cant be resolved I will have to look for an alternative plugin as I have members who require to use this option. 

I have emailed over my details to you now. 

Many thanks
